spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://db:5432/elobaby
  jpa:
    show-sql: 'true'

# Logs
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /elobaby
  port: 8080

cors:
  allowed-origin: https://elo-baby.leurquin.org
  insecure: false
  postman-testing : false


jwt:
  secret: ${JWT_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  token-duration: 1800               # default: 30 min
  refresh-token-duration: 2592000      # default: 1 month
  issuer: elobaby